# This is a basic workflow to help you get started with Actions

name: ustvgo_m3ugrabber

# Controls when the workflow will run
on:
  workflow_dispatch:
  # Run 6 Hours after https://github.com/bitsbb01/iptvcat-scrapper
  # 12.10 UTC Time, 06.10 Central Time
  # Now runs every 1 hrs to make sure the m3u is upto date.
  schedule:
#    - cron: "10 6 * * *"
    - cron: "0 0/1 * * *"
  push:
    branches:
    - master
    - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # 
      - name: config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
       
             
      - name: Cleanup Files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git rm ./*.m3u
          
          
      - name: Push changes for old files
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.scrapper_token }}
          branch: ${{ github.ref }}
          
      - name: Commit All Files
        uses: zwaldowski/git-commit-action@v1
        with:
             commit_message: Updated by Bot - ${{ steps.date.outputs.date }}
             working_directory: .
          
      - name: uninstall tqdm
        run: |
          pip uninstall tqdm
          python3 -m pip install tqdm

      - name: run script
        run: |
          chmod +x autorun.sh
          ./autorun.sh
      
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date '+%Y-%m-%d')"
      
      - name: Commit All Files
        uses: zwaldowski/git-commit-action@v1
        with:
             commit_message: Updated by Bot - ${{ steps.date.outputs.date }}
             working_directory: .

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.scrapper_token }}
          branch: ${{ github.ref }}
